version: '3.7'
services:
  web:
    image: nginx-phpfpm
    restart: always
    container_name: nginx_ujian
    ports:
     - "80:80"
    volumes:
      - "./:/var/www/html"
      - "./site.conf:/etc/nginx/sites-enabled/default:ro"
    # depends_on:
      # - db
  # db:
    # image: bitnami/postgresql:latest
    # restart: always
    # container_name: db_ujian
    # ports:
        # - "5432:5432"
    # expose:
        # - "5432"
    # volumes:
        # - "pgsql:/bitnami/postgresql"
    # environment:
        # POSTGRESQL_USERNAME: 'postgres'
        # POSTGRESQL_PASSWORD: 'postgres'
        # POSTGRESQL_DATABASE: 'ujian_dbs'
  # pdf:
    # image: ciricihq/wkhtmltopdf-aas
    # restart: always
    # container_name: wkhtmltopdf
# volumes:
  # pgsql:
    # name: pgsql_ujian
